### ISSUE TITLE
[PE-D][Tester A] Feature mentioned in User Guide not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F14-4/tp#193]
**Describe the bug**

After loaning out a book, it does not appear at the top of the book list as mentioned in the User Guide. Perhaps this is due to an incomplete feature implementation.

**Expected behaviour**

Book loaned will be brought to the top of the book list but instead, a book not on loan is on top of the book that is loaned out.

**Screenshots**

*After loaning out a book:*

![image.png](https://raw.githubusercontent.com/LimAiLin/ped/main/files/704871e9-de83-4fe9-a81e-6eda5fb08bc4.png)

*User Guide:*

![image.png](https://raw.githubusercontent.com/LimAiLin/ped/main/files/235ac453-20bf-452b-be52-96ccedd30f87.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: LimAiLin/ped#6

**Comment by sprintaway** [comment]
Add in user guide to state reflush and reassigning loan order to top after closing and reopening the app.
