### ISSUE TITLE
[PE-D][Tester D] Find command unable to search for book loan dates in the user or book list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F14-4/tp#198]
![Screenshot 2022-10-28 at 7.23.29 PM.png](https://raw.githubusercontent.com/sherylkong18/ped/main/files/8f437a88-4c34-49aa-becc-59f709b3835d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: sherylkong18/ped#3

**Comment by TYKCodes** [comment]
Rebutted; User Guide specified that `Find` is meant to search for:

- `Book` --> Title or Author
- `Person` --> Name
