### ISSUE TITLE
[PE-D][Tester D] Incorrect error message when input for Loan command is wrong.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F14-4/tp#201]
![Screenshot 2022-10-28 at 7.33.52 PM.png](https://raw.githubusercontent.com/sherylkong18/ped/main/files/209cdf79-107d-44cf-9753-004b671e4dec.png)

As shown here the error message displayed is "Unable to parse as date" which is not related to the command.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: sherylkong18/ped#6

**Comment by parth-io** [comment]
This is a bug, not a flaw

**Comment by TYKCodes** [comment]
Error Message should include correct format of the date
