### ISSUE TITLE
[PE-D][Tester D] Theme feature shown as "Coming soon" in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F14-4/tp#204]
![Screenshot 2022-10-28 at 10.50.47 PM.png](https://raw.githubusercontent.com/sherylkong18/ped/main/files/bffec6e8-8645-40d5-8fb7-7482c8a521c9.png)

In the app it is already implemented

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: sherylkong18/ped#9

**Comment by TYKCodes** [comment]
Linked with #173

**Comment by Edfernape** [comment]
closing. have updated the user guide accordingly
